### PR TITLE
Apply some upstream patches

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by VicDeo** [comment]
@LukasReschke please have a look

**Comment by LukasReschke** [comment]
Awesome. Patch is confirmed :+1:

Any easy way we can get that to stable7 and 6 as well?

**Comment by VicDeo** [comment]
@LukasReschke cherry-pickable 
https://github.com/owncloud/documents/pull/438
https://github.com/owncloud/documents/pull/439

**Comment by LukasReschke** [comment]
Let's merge this then.

**Pull request merged**
