### PR TITLE
Cast share id to string

### PR DESCRIPTION
**Pull request by PVince81**
@VicDeo @DeepDiver1975 @butonic 

To be backported to:
- stable9.1
- stable9

### CODE REVIEW

**Comment by PVince81** [comment]
@VicDeo please review

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
Will take care about backports

**Comment by rperezb** [comment]
@davivel @dragotin @danimo could this affect clients?
thx

**Comment by VicDeo** [comment]
@rperezb this one - definitely no. Not sure about that one https://github.com/owncloud/core/pull/25432

**Comment by VicDeo** [comment]
stable9.1: #651 
stable9: #650

**Pull request merged**
