### PR TITLE
Webodf sync with 0.5.7-66-g25bf592

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes 
https://github.com/owncloud/documents/issues/177 https://github.com/owncloud/documents/issues/321 https://github.com/owncloud/documents/issues/469

Test Plan
- [x]  change text size: select text then use spinner in toolbar to increase size
- [x] change font effect (bold, italic) on selection
- [x] avatars too close from each other, missing names (Fixed)
- [x] share with another local user and edit (from the toolbar menu)
- [x] share with link
- [x] change styles in Format menu like color, alignment
- [x] zoom in/out
- [x] indent
- [x] input method (chinese)

TODO: 
- [x] Update build script and patches

### CODE REVIEW

**Comment by VicDeo** [comment]
@PVince81 May I ask you to have a quick look?
Especially regarding Chinese input

**Comment by VicDeo** [comment]
@karlitschek 
Direct formatting issues are no longer reproducible with this sync

**Comment by jospoortvliet** [comment]
Awesome, Vic!!! It would rock to see this make it in 8.1... Whoah.

**Comment by karlitschek** [comment]
yay. Thanks @VicDeo What is your opinion about putting this in 8.1 ? 
Something missing?

**Comment by VicDeo** [comment]
@karlitschek 
It works quite stable according to my tests and brings new features like indentation buttons and collab annotations support. 
In addition it fixes copy/paste with keyboard shortcuts in Firefox
I think it is worth including into 8.1.

**Comment by karlitschek** [comment]
awesome!!!!
we should also blog about this. @jospoortvliet

**Comment by PVince81** [comment]
Chinese input method works (tested with fcitx 4.2.8 on Firefox 37.0.2)

**Comment by VicDeo** [comment]
@karlitschek @jospoortvliet Merged.

**Pull request merged**
