### PR TITLE
Fix editing document problem

### PR DESCRIPTION
**Pull request by tpayen**
Try to load index.php file but it doesn't exist. Use generateURL instead

### CODE REVIEW

**Comment by VicDeo** [comment]
@tpayen Thanks a lot!
:+1:

**Comment by VicDeo** [comment]
Fixes https://github.com/owncloud/documents/issues/564

**Comment by VicDeo** [comment]
@karlitschek  8.1 is not affected.
Backport to 8.2?

**Comment by karlitschek** [comment]
backport makes sense. Thanks

**Pull request merged**
