### PR TITLE
Fix preview of documents

### PR DESCRIPTION
**Pull request by Urknaller**

### CODE REVIEW

**Comment by josh4trunks** [comment]
:+1:

**Comment by josh4trunks** [comment]
@VicDeo 
This worked for me. I'm wondering if you've seen reviewed this yet?
Thanks,

**Comment by VicDeo** [comment]
@Urknaller the base branch seems to be wrong. Everything works in OC8 without this PR so I think 7.x is only affected

**Comment by josh4trunks** [comment]
@VicDeo
I thought I tested this on OC8, I'll double check my test, but for me this was needed to get previews working in the documents app.

**Comment by josh4trunks** [comment]
@VicDeo
I confirmed my earlier testing. OC8.0.2 previews aren't shown in the Documents app, even with all preview providers enabled. This change fixed it for me.

Are previews in the Documents app working for you in OC8?

**Comment by VicDeo** [comment]
@josh4trunks anyway this option should be bool https://github.com/owncloud/core/blob/master/config/config.sample.php#L618

Did you check that `'enable_previews' => false,` disables previews with this change?

**Comment by VicDeo** [comment]
@josh4trunks I guess reverting this patch and explicitly enabling previews with 
`'enable_previews' => true,`
will have the same effect

**Comment by josh4trunks** [comment]
I didn't check that. I'll check tonight and report back.

**Comment by josh4trunks** [comment]
@VicDeo that is true. if you don't have this patch, the Documents app always thinks previews are disabled.

**Comment by josh4trunks** [comment]
Ok, I think I understand what you were saying @VicDeo about the bolean

---

Here's what I witnessed in the Documents app with ``OC\Preview\OpenDocument`` enabled
**Normal**
* `enable_previews` unset - no previews
*  `'enable_previews' => false` - no previews
* `'enable_previews' => true` - previews

**With this patch**
* `enable_previews` unset - >> **previews** <<
*  `'enable_previews' => false` - no previews
* `'enable_previews' => true` - previews

What I believe is happening is this patch it setting the default (`enable_previews` = unset) to 'false' which is a string and when interpreted as a bolean is true.

---

I am going to take back my thumbs up and instead suggest we make the default true. This is how I believe the files app works. It assumes you want previews (unset means enabled), but only for the file types you explicitly enable. I workaround for now is to set `'enable_previews' => true` and enable document preview_providers.

**Comment by VicDeo** [comment]
@josh4trunks welcome to https://github.com/owncloud/documents/pull/467 then

**Comment by VicDeo** [comment]
@Urknaller Thanks for this PR
Your solution works but is not straightforward. It works because string `'false'` is casted to boolean `true` in template.

**Pull request closed without merging**
