### PR TITLE
Kill OC_FileProxy references

### PR DESCRIPTION
**Pull request by VicDeo**
Fixes https://github.com/owncloud/documents/issues/472

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by jancborchardt** [comment]
Still doesn’t load any document. Shows the overlay, but no document.

JS console:
```
GET http://localhorst/owncloud/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)
documents.js?v=6b0668727fdd3ce1c4be08ad0f56d376:376 joining session 2035
VM348:482 HEAD http://localhorst/owncloud/index.php/apps/documents/ajax/genesis/onmjklgl4qzcrzip5dqf1kqosw2tay?requesttoken=VqfYmssvRDUH+emMa99DWF7uFzGwGm 412 (Precondition failed)getFileSize @ VM348:482Zip @ VM348:3977OdfContainer @ VM348:5555load @ VM348:8425initDocLoading @ Editor.js:129Editor.openSession @ Editor.js:247(anonymous function) @ documents.js?v=6b0668727fdd3ce1c4be08ad0f56d376:365c @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:4p.fireWith @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:4l @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:5c @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:4p.fireWith @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:4p.fire @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:4x.extend.dequeue @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:5r.complete @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:6c @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:4p.fireWith @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:4l @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:6x.fx.tick @ jquery.min.js?v=6b0668727fdd3ce1c4be08ad0f56d376:6
VM348:345 GET http://localhorst/owncloud/index.php/apps/documents/ajax/genesis/onmjklgl4qzcrzip5dqf1kqosw2tay?requesttoken=VqfYmssvRDUH+emMa99DWF7uFzGwGm 412 (Precondition failed)readFile @ VM348:345read @ VM348:351(anonymous function) @ VM348:3982xhr.onreadystatechange @ VM348:471
VM348:448 GET http://localhorst/owncloud/index.php/apps/documents/ajax/genesis/onmjklgl4qzcrzip5dqf1kqosw2tay?requesttoken=VqfYmssvRDUH+emMa99DWF7uFzGwGm 412 (Precondition failed)loadXML @ VM348:448loadFromXML @ VM348:5423(anonymous function) @ VM348:5558(anonymous function) @ VM348:3984(anonymous function) @ VM348:359handleResult @ VM348:340
VM348:248 WARNING: refreshOdf called but ODF was not DONE.
33VM348:248 will be back later...
```
owncloud.log:
```
{"reqId":"0QoGjxsa664M5W0SDpl1","remoteAddr":"127.0.0.1","app":"no app in context","message":"CSRF check failed","level":0,"time":"2015-04-23T15:09:51+00:00","method":"HEAD","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/genesis\/onmjklgl4qzcrzip5dqf1kqosw2tay?requesttoken=VqfYmssvRDUH+emMa99DWF7uFzGwGm"}
{"reqId":"wqvnBwbtKWLeYVE9s0R7","remoteAddr":"127.0.0.1","app":"no app in context","message":"CSRF check failed","level":0,"time":"2015-04-23T15:09:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/genesis\/onmjklgl4qzcrzip5dqf1kqosw2tay?requesttoken=VqfYmssvRDUH+emMa99DWF7uFzGwGm"}
{"reqId":"A9v4Q2U9PWAUkpYAp\/4z","remoteAddr":"127.0.0.1","app":"no app in context","message":"CSRF check failed","level":0,"time":"2015-04-23T15:09:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/documents\/ajax\/genesis\/onmjklgl4qzcrzip5dqf1kqosw2tay?requesttoken=VqfYmssvRDUH+emMa99DWF7uFzGwGm"}
```

**Comment by VicDeo** [comment]
@jancborchardt any or one specific?

**Comment by jancborchardt** [comment]
Any

**Comment by VicDeo** [comment]
@jancborchardt is it better now? 
browser cache might need cleaning

**Comment by jancborchardt** [comment]
Yup, works now. :+1:

**Comment by AisoPlee** [comment]
I still have this issue when creating or editing any Document - just white loading page.

And this is, what the log tells:
{"reqId":"iWDAGVFHF0Xgmw1pcyJl","remoteAddr":"212.243.7.194","app":"PHP","message":"Class 'OC_FileProxy' not found at \/var\/www\/virtual\/david\/html\/owncloud8\/apps\/documents\/lib\/genesis.php#90","level":3,"time":"2015-07-08T09:24:32+00:00"}

are there any prerequisites that should be checked?

Owncloud 8.1 stable

**Comment by jancborchardt** [comment]
@AisoPlee can you open this as a new issue please? Thank you! :)

**Pull request merged**
