### PR TITLE
Fixes broken documents view 

### PR DESCRIPTION
**Pull request by VicDeo**
getData on search result is not always an array now
 #609

### CODE REVIEW

**Comment by VicDeo** [comment]
@enoch85 Can you confirm that it fixes the issue for master?

**Comment by enoch85** [comment]
Thanks @VicDeo My DEV VM is broken right now, will test asap.

**Comment by enoch85** [comment]
:-1: This does not fix the grey icon. Though it might fix something else.

**Comment by VicDeo** [comment]
@enoch85 It works for me. Note docs before are just empty objects and after they are not.

docs-before

docs-after

**Comment by enoch85** [comment]
Ok, fine then. :) Thanks for the fix!

**Comment by VicDeo** [comment]
@enoch85 If it doesn't work for you please check a response to `ajax/documents/list` request and post it to the issue you opened.

**Pull request merged**
