### PR TITLE
LibreOffice config should be in instance temp folder

### PR DESCRIPTION
**Pull request by oparoz**
Make sure that the LibreOffice configuration folder ends up in the temp folder of the OC instance

### CODE REVIEW

**Comment by RealRancor** [comment]
Hi,

any reason why this wasn't merged yet? OC8 used this now since quite some time after the merge of https://github.com/owncloud/core/pull/10827

**Comment by oparoz** [comment]
I didn't realise it wasn't and this should get in ASAP. The app won't work properly without it.
@VicDeo

**Comment by VicDeo** [comment]
@oparoz sorry, please resubmit against master

**Comment by oparoz** [comment]
@VicDeo  https://github.com/owncloud/documents/pull/474

**Comment by VicDeo** [comment]
@oparoz thanks!
Can you change conversion test accordingly https://github.com/owncloud/documents/blob/master/lib/config.php#L28

**Comment by oparoz** [comment]
Will do

**Comment by VicDeo** [comment]
Closing in favor of https://github.com/owncloud/documents/pull/474

**Pull request closed without merging**
